### ISSUE TITLE
Add config for Spotify web client running on Chromium

### ISSUE THREAD

**Issue by redfast00** [Tehforsch/striputary#7]
I don't use the native Spotify player, but use the Spotify web client (open.spotify.com) on Chromium. Would it be possible to support this as well? Thank you in advance!

**Comment by redfast00** [comment]
Here's what I've got: I got the dbus_bus_name with dbus-monitor and the sink_name from pavucontrol, but this doesn't seem to work yet

```
"chromium" => Ok(ServiceConfig {
                sink_name: "Chromium".to_string(),
                dbus_bus_name: "org.mpris.MediaPlayer2.Player".to_string(),
            }),
```

**Comment by redfast00** [comment]
with `sink_name` as `'Playback'`, it seems to do something, but it doesn't entirely work yet

**Comment by Tehforsch** [comment]
Thanks for looking into this. When I tried it with your changes, I noticed two problems:
1. Chromium (and Firefox) register their mpris interface under the service name `chromium.instance<INSTANCE_ID>`, so that striputary can't know the exact service name in advance. This is easy enough to fix by looking over the list of services for a matching entry.
2. The next problem is that chromium seems to send very inconsistent data via MPRIS. Missing album entries, no track numbers and rewinding an already playing track does not send a new entry (most likely connected to #5) . In fact, due to #5, I am beginning to think my version of spotify native which properly sends all metadata reliably is the exception. This will make it a bit more complicated than I initially thought, since I'll have to find a way to deal with missing metadata. I'll attempt to fix this in the coming weeks.

**Comment by redfast00** [comment]
@Tehforsch Thank you for looking into this! I'd be fine with some metadata not being set or set to the empty string in case it's unavailable :)

**Comment by Tehforsch** [comment]
This ended up being more complicated than I thought it would initially be, since spotify-chromium sends incredibly unreliable metadata for the songs. I had to add more graceful handling of missing metadata and seem to have a working version on #8 . I haven't merged it yet because I am not sure how robust the current solutions are. It would be great if you could test it, @redfast00

**Comment by redfast00** [comment]
It does seem to work now (at least for one song, that is), thanks :)
