### ISSUE TITLE
Listen while recording

### ISSUE THREAD

**Issue by redfast00** [Tehforsch/striputary#9]
I'd like to listen to the music while it's recording. Currently, I manually do the following:

1. Start striptuary (this creates the striptuary sink)
2. Execute `pactl get-default-sink`, this gives the default sink name, for this example, we'll assume it's `bluez_sink.AA_BB_CC_DD_EE_FF.a2dp_sink` (my bluetooth headphones)
3. Create a combination sink: `pacmd load-module module-combine-sink sink_name=combination-sink sink_properties=device.description=AudioAndStriptuaryCombination slaves=striptuary,bluez_sink.AA_BB_CC_DD_EE_FF.a2dp_sink`
4. Make the audio program use the AudioAndStriptuaryCombination sink instead of the Null Sink (created by striptuary)

Note that it's possible to set the name of a sink, this should probably also be done for the sink Striptuary creates to make it clearer for users.

This could maybe be a commandline option?

**Comment by Tehforsch** [comment]
Took me a while to work on this: I implemented it in #10 . Would you mind testing if it works for you?
You can pass `--monitor` as a commandline option to listen to the output or specify
`monitor: true`
 in the config file. The sinks should now also be properly named (it actually had a "name" before, but it turns out the string that `pavucontrol` displays is actually the description, not the name)

**Comment by redfast00** [comment]
Oops, seems that I forgot about this, sorry for not getting back to you earlier. The monitor feature does seem to work, thank you for that!
